<?php
$destinations = [
    "jungle-safari" => [
        "name" => "Jungle Safari, Nava Raipur",
        "image" => "assets/images/tours/jungle-safari-raipur.jpg",
        "alt" => "Jungle Safari in Nava Raipur - Raipur Taxi Tour",
        "location" => "Sector 39, Nava Raipur, Chhattisgarh 492101",
        "map_link" => "https://goo.gl/maps/abc123safari",
        "short_desc" => "Asia's largest man-made safari featuring Tiger, Bear, and Herbivore enclosures.",
        "distance" => "35 KM",
        "travel_time" => "45 Mins",
        "best_time" => "October to March",
        "highlights" => "Tiger Safari, Herbivore Safari, Bear Safari, Khandwa Reservoir",
        "duration" => "4-5 Hours",
        "taxi_option" => "Local / Half-Day Rental",
        "overview" => "Nandan Van Jungle Safari in Nava Raipur is a world-class zoo and safari park. It spans over 800 acres and offers thrilling bus safaris where you can spot majestic Bengal tigers, bears, and various herbivores roaming in their natural habitats. The area also encompasses the beautiful Khandwa Reservoir, attracting numerous migratory birds.",
        "why_visit" => "Perfect for wildlife enthusiasts and families looking for a day trip close to Raipur city.",
        "things_to_do" => "Take the guided bus safari, visit the botanical garden, enjoy boating at Khandwa reservoir.",
        "nearby" => "Purkhouti Muktangan, MM Fun City"
    ],
    "ghatarani" => [
        "name" => "Ghatarani Waterfalls",
        "image" => "assets/images/tours/ghatarani-waterfall-raipur.jpg",
        "alt" => "Ghatarani Waterfalls near Raipur - Outstation Cab",
        "location" => "Ghatarani, Jamui, Chhattisgarh 493114",
        "map_link" => "https://goo.gl/maps/ghatarani123",
        "short_desc" => "The largest waterfall in Chhattisgarh, surrounded by lush green forests and a sacred temple.",
        "distance" => "85 KM",
        "travel_time" => "2 Hours",
        "best_time" => "July to December",
        "highlights" => "Scenic Waterfall, Jatmai-Ghatarani Temple, Trekking",
        "duration" => "Half Day",
        "taxi_option" => "Outstation / Round Trip",
        "overview" => "Ghatarani is renowned as the largest waterfall in Chhattisgarh. Surrounded by dense forests and a revered local temple, it becomes a spectacular sight during and right after the monsoons. The gentle trek to the base of the waterfall makes it an adventurous yet spiritual journey.",
        "why_visit" => "A breathtaking natural escape offering both spiritual peace and scenic beauty, perfect for a weekend getaway.",
        "things_to_do" => "Bathe in the natural pools, visit the Ghatarani Mata Temple, enjoy a forest picnic.",
        "nearby" => "Jatmai Temple (25 KM away)"
    ],
    "sirpur" => [
        "name" => "Sirpur Historical Site",
        "image" => "assets/images/tours/sirpur-historical-site.jpg",
        "alt" => "Ancient Lakshmana Temple Sirpur - Raipur Taxi Service",
        "location" => "Sirpur, Mahasamund District, Chhattisgarh",
        "map_link" => "https://goo.gl/maps/sirpur123",
        "short_desc" => "An ancient town featuring 7th-century Buddhist monasteries, Hindu temples, and Jain viharas.",
        "distance" => "80 KM",
        "travel_time" => "1.5 Hours",
        "best_time" => "October to March",
        "highlights" => "Lakshmana Temple, Surang Tila, Anand Prabhu Kudi Vihar",
        "duration" => "5-6 Hours",
        "taxi_option" => "Outstation / Full-Day Rental",
        "overview" => "Sirpur is a deeply historical and archaeological site on the banks of the Mahanadi river. Once the capital of the Somavanshi kings in the 7th and 8th centuries, it is a treasure trove of brick temples, Buddhist monasteries, and ancient statues. The iconic Lakshmana Temple is one of the finest brick temples in India.",
        "why_visit" => "A must-visit for history buffs, architecture lovers, and spiritual seekers wanting to explore ancient India.",
        "things_to_do" => "Explore the brick architecture of Lakshmana Temple, visit the excavated Buddhist Viharas, attend the Sirpur National Dance and Music Festival (in winter).",
        "nearby" => "Barnawapara Wildlife Sanctuary"
    ],
    "chitrakote" => [
        "name" => "Chitrakote Waterfalls",
        "image" => "assets/images/tours/chitrakote-waterfalls.jpg",
        "alt" => "Chitrakote Waterfalls Bastar - Taxi Tour Package",
        "location" => "Tiratha, Bastar District, Chhattisgarh 494001",
        "map_link" => "https://goo.gl/maps/chitrakote123",
        "short_desc" => "Often called the Niagara Falls of India, this majestic horseshoe-shaped waterfall is a natural wonder.",
        "distance" => "280 KM",
        "travel_time" => "6 Hours",
        "best_time" => "August to November",
        "highlights" => "Horseshoe Waterfall, Indravati River, Boating, Sunset View",
        "duration" => "2 Days / 1 Night",
        "taxi_option" => "Outstation Multi-Day Tour",
        "overview" => "Located in the Bastar district, Chitrakote is the widest waterfall in India. During the monsoon season, the Indravati river flows with immense force, creating a horseshoe drop of about 30 meters. The misty atmosphere and rainbows forming over the falls make it a photographer's paradise.",
        "why_visit" => "To witness the raw power of nature at India's widest waterfall and explore the tribal culture of Bastar.",
        "things_to_do" => "Take a boat ride to the base of the falls, camp nearby, explore local Bastar handicrafts.",
        "nearby" => "Tirathgarh Waterfalls, Kanger Valley National Park, Danteshwari Temple"
    ],
    "barnawapara" => [
        "name" => "Barnawapara Wildlife Sanctuary",
        "image" => "assets/images/tours/barnawapara-wildlife-sanctuary.jpg",
        "alt" => "Barnawapara Wildlife Sanctuary - Tour Travel Cab",
        "location" => "Mahasamund District, Chhattisgarh",
        "map_link" => "https://goo.gl/maps/barnawapara123",
        "short_desc" => "A thriving forest reserve famous for leopards, sloth bears, Indian gaur, and exotic birds.",
        "distance" => "100 KM",
        "travel_time" => "2.5 Hours",
        "best_time" => "November to June",
        "highlights" => "Jungle Safari, Bird Watching, Nature Camping",
        "duration" => "Full Day or Weekend Trip",
        "taxi_option" => "Outstation / Tour Package",
        "overview" => "Barnawapara Wildlife Sanctuary is named after the twin forest villages of Bar and Nawapara. The sanctuary boasts a diverse topography of flat and hilly terrain covered with lush green teak, sal, and bamboo trees. It is home to leopards, sloth bears, flying squirrels, and a large population of common langurs.",
        "why_visit" => "Ideal for nature lovers wanting an authentic jungle safari experience away from commercialized zones.",
        "things_to_do" => "Book an open-jeep safari, stay at an eco-resort, bird watching in the early morning.",
        "nearby" => "Sirpur Historical Site"
    ],
    "purkhouti" => [
        "name" => "Purkhouti Muktangan",
        "image" => "assets/images/tours/purkhouti-muktangan-raipur.jpg",
        "alt" => "Purkhouti Muktangan Nava Raipur Tourism",
        "location" => "Sector 24, Nava Raipur, Chhattisgarh",
        "map_link" => "https://goo.gl/maps/purkhouti123",
        "short_desc" => "An expansive open-air museum displaying the rich tribal culture, folk art, and heritage of Chhattisgarh.",
        "distance" => "25 KM",
        "travel_time" => "40 Mins",
        "best_time" => "All year round (Evenings)",
        "highlights" => "Tribal Art, Sculptures, Landscaped Gardens, Cultural Models",
        "duration" => "2-3 Hours",
        "taxi_option" => "Local Rental / Half-Day",
        "overview" => "Inaugurated by Dr. A.P.J. Abdul Kalam, Purkhouti Muktangan is an open-air museum and park in Nava Raipur. It provides a fascinating glimpse into the vibrant culture, tribal traditions, architectures, and arts of various tribes of Chhattisgarh through life-sized dioramas and beautifully painted structures.",
        "why_visit" => "To understand the rich cultural tapestry of Chhattisgarh in a single, beautifully landscaped location.",
        "things_to_do" => "Walk through the tribal villages models, photography, relax in the vast gardens.",
        "nearby" => "Jungle Safari, Muktangan Light & Sound Show"
    ]
];

$tour_packages = [
    ["title" => "Raipur Local Sightseeing", "duration" => "8 Hours / 80 KM", "desc" => "Explore Budha Talab, Marine Drive, Mahant Ghasidas Museum, and local markets."],
    ["title" => "Nava Raipur Tour", "duration" => "Half Day", "desc" => "Visit Jungle Safari, Purkhouti Muktangan, and the modern marvels of the smart city."],
    ["title" => "Sirpur & Barnawapara Heritage Tour", "duration" => "1 Day", "desc" => "Ancient temples of Sirpur followed by a thrilling jungle safari in Barnawapara."],
    ["title" => "Ghatarani & Jatmai Waterfall Tour", "duration" => "1 Day", "desc" => "A scenic drive to the lush green forests and majestic waterfalls."],
    ["title" => "Bastar Adventure (Chitrakote)", "duration" => "2 Days / 1 Night", "desc" => "Visit India's Niagara (Chitrakote), Tirathgarh falls, and Kanger Valley National Park."],
    ["title" => "Rajim Kumbh Darshan", "duration" => "Half Day", "desc" => "A spiritual trip to the 'Prayag of Chhattisgarh' at the confluence of three rivers."]
];
?>
